/** Gitmoji choices used to steer model output toward gitmoji.dev conventions. */
export const GITMOJI_REFERENCE = [
  '🎨 :art: improve structure or formatting',
  '⚡️ :zap: improve performance',
  '🔥 :fire: remove code or files',
  '🐛 :bug: fix a bug',
  '🚑️ :ambulance: apply a critical hotfix',
  '✨ :sparkles: introduce new features',
  '📝 :memo: add or update documentation',
  '🚀 :rocket: deploy changes',
  '💄 :lipstick: add or update UI and style files',
  '🎉 :tada: begin a project',
  '✅ :white_check_mark: add, update, or pass tests',
  '🔒️ :lock: fix security or privacy issues',
  '🔐 :closed_lock_with_key: add or update secrets',
  '🔖 :bookmark: release or version tags',
  '🚨 :rotating_light: fix compiler or linter warnings',
  '💚 :green_heart: fix CI build',
  '⬇️ :arrow_down: downgrade dependencies',
  '⬆️ :arrow_up: upgrade dependencies',
  '📌 :pushpin: pin dependencies',
  '👷 :construction_worker: add or update CI build system',
  '📈 :chart_with_upwards_trend: add analytics or tracking code',
  '♻️ :recycle: refactor code',
  '➕ :heavy_plus_sign: add a dependency',
  '➖ :heavy_minus_sign: remove a dependency',
  '🔧 :wrench: add or update configuration files',
  '🔨 :hammer: add or update development scripts',
  '🌐 :globe_with_meridians: internationalization and localization',
  '✏️ :pencil2: fix typos',
  '⏪️ :rewind: revert changes',
  '🔀 :twisted_rightwards_arrows: merge branches',
  '📦️ :package: add or update compiled files or packages',
  '👽️ :alien: update code due to external API changes',
];
